/**
 * Deterministic compiler: S5's automation_model JSON -> a Playwright
 * .spec.ts file. Deliberately not an LLM call -- S5 decided *what* to do
 * and assert; this module only decides how to spell that out as Playwright
 * API calls, so it can never silently drop or weaken an assertion the
 * model actually contains.
 */
import type { Assertion, AutomationModel, S5Output, Step } from "./types.js";

function substitute(value: unknown, data: Record<string, unknown>): unknown {
  if (typeof value !== "string") return value;
  return value.replace(/\{\{(\w+)\}\}/g, (match, key: string) =>
    key in data ? String(data[key]) : match
  );
}

/** Quote unquoted [name=…] values so `name=Log in` is valid Playwright. */
function quoteLocatorAttrs(locator: string | undefined): string | undefined {
  if (!locator) return locator;
  return locator.replace(/\[(\w+)=([^\]]+)\]/g, (full, attr: string, raw: string) => {
    const value = raw.trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      return full;
    }
    if (/[\s,]/.test(value)) {
      return `[${attr}=${JSON.stringify(value)}]`;
    }
    return full;
  });
}

function renderStep(step: Step, data: Record<string, unknown>): string {
  switch (step.type) {
    case "navigate":
      return `  await page.goto(${JSON.stringify(step.target)});`;
    case "fill":
      return `  await page.locator(${JSON.stringify(quoteLocatorAttrs(step.locator))}).fill(${JSON.stringify(
        substitute(step.value, data)
      )});`;
    case "click":
      return `  await page.locator(${JSON.stringify(quoteLocatorAttrs(step.locator))}).click();`;
    case "select":
      return `  await page.locator(${JSON.stringify(quoteLocatorAttrs(step.locator))}).selectOption(${JSON.stringify(
        substitute(step.value, data)
      )});`;
    case "check":
      return `  await page.locator(${JSON.stringify(quoteLocatorAttrs(step.locator))}).check();`;
    case "wait":
      // Per AGENT_INSTRUCTIONS.md 13.1: hard-coded sleeps are never valid.
      // Every 'wait' step in the model must carry a justification (enforced
      // by schemas/s5.schema.json); this compiles to a real wait condition.
      return (
        `  // wait justified: ${step.justification ?? "unspecified"}\n` +
        `  await page.waitForLoadState('networkidle');`
      );
    case "request":
      return (
        `  const response = await request.fetch(${JSON.stringify(step.endpoint)}, ` +
        `{ data: ${JSON.stringify(substitute(step.payload, data))} });`
      );
    default:
      return `  // TODO: unsupported step type '${(step as Step).type}' -- escalate to S5, do not hand-fix.`;
  }
}

function isNegativeVisible(expected: unknown): boolean {
  return expected === false || expected === "false" || expected === 0 || expected === "0";
}

function renderAssertion(assertion: Assertion): string {
  const proves = `// proves ${assertion.test_case_id}`;
  switch (assertion.type) {
    case "visible":
      if (isNegativeVisible(assertion.expected_value)) {
        return `  await expect(page.locator(${JSON.stringify(quoteLocatorAttrs(assertion.target))})).not.toBeVisible(); ${proves}`;
      }
      return `  await expect(page.locator(${JSON.stringify(quoteLocatorAttrs(assertion.target))})).toBeVisible(); ${proves}`;
    case "text_match":
      return `  await expect(page.locator(${JSON.stringify(quoteLocatorAttrs(assertion.target))})).toHaveText(${JSON.stringify(
        assertion.expected_value
      )}); ${proves}`;
    case "status_code":
      return `  expect(response.status()).toBe(${JSON.stringify(assertion.expected_value)}); ${proves}`;
    case "schema_match":
      return `  // TODO: schema_match against ${JSON.stringify(assertion.expected_value)} ${proves}`;
    case "response_time":
      return `  // TODO: response_time assertion (SLA ${JSON.stringify(assertion.expected_value)}ms) ${proves}`;
    case "header_match":
      return `  // TODO: header_match assertion ${proves}`;
    default:
      return `  // TODO: unsupported assertion type '${(assertion as Assertion).type}' -- escalate to S5. ${proves}`;
  }
}

export function compileAutomationModel(s5: S5Output, testData: Record<string, unknown> = {}): string {
  const { automation_model, test_case_id, layer, script_id } = s5;
  const needsRequest = layer !== "UI";
  const fixtureArgs = needsRequest ? "{ page, request }" : "{ page }";

  const lines: string[] = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Generated by the Automation Model Compiler from S5 script_id=${script_id}.`,
    `// Do not hand-edit -- edit the S5 automation_model and recompile.`,
    `test(${JSON.stringify(test_case_id)}, async (${fixtureArgs}) => {`,
  ];

  const steps: Step[] = [...automation_model.setup, ...automation_model.actions];
  for (const step of steps) lines.push(renderStep(step, testData));
  for (const assertion of automation_model.assertions) lines.push(renderAssertion(assertion));

  lines.push(`});`, ``);
  return lines.join("\n");
}

export function outputFileNameFor(s5: S5Output): string {
  return `${s5.test_case_id}.spec.ts`;
}
